---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build
        run: cargo build
      - name: Lint
        run: cargo clippy
      - name: Check Formatting
        run: cargo fmt --check
      - name: Run Tests
        run: cargo test
