---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build
        run: cargo build
      - name: Lint
        run: cargo clippy
      - name: Check Formatting
        run: cargo fmt --check
      - name: Run Tests
        run: cargo test
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: >-
            -Cinstrument-coverage
            -Zprofile
            -Ccodegen-units=1
            -Cinline-threshold=0
            -Clink-dead-code
            -Coverflow-checks=off
            -Cpanic=abort
            -Zpanic_abort_tests
      - id: coverage
        name: Collect code coverage
        uses: actions-rs/grcov@v0.1.5
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          verbose: true
          fail_ci_if_error: true
          files: ${{ steps.coverage.outputs.report }}
