---
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install github:cachix/devenv/v0.6.3
        shell: sh
      - name: Build
        run: devenv shell cargo build
      - name: Lint
        run: devenv shell cargo clippy
      - name: Check Formatting
        run: devenv shell cargo fmt --check
      - name: Run Tests
        run: devenv shell cargo test
        env:
          CARGO_INCREMENTAL: 0
          RUSTC_BOOTSTRAP: 1
          RUSTFLAGS: -Cinstrument-coverage -Zprofile
          LLVM_PROFILE_FILE: shady-%p-%m.profraw
      - id: coverage
        name: Collect code coverage
        uses: actions-rs/grcov@v0.1.5
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          verbose: true
          fail_ci_if_error: true
          files: ${{ steps.coverage.outputs.report }}
