---
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Lint
        run: cargo clippy
      - name: Check Formatting
        run: cargo fmt --check
      - name: Run Tests
        run: cargo test
